import {getCliClient} from 'sanity/cli'

const client = getCliClient({
  apiVersion: '2026-07-27',
})

const keyed = (key, value) => ({_key: key, ...value})

const resume = {
  _id: 'resume',
  _type: 'resume',
  name: 'Randal Herndon',
  headline: 'Digital Marketing & Web Experience Leader',
  location: 'Phoenix, AZ',
  phone: '314-435-6992',
  email: 'randal.herndon@gmail.com',
  linkedinUrl: 'https://linkedin.com/in/randalherndon',
  websiteUrl: 'https://randalherndon.com',
  summary:
    'Digital marketing and web experience leader with 15+ years of experience building, optimizing, and managing high-performing websites, digital campaigns, analytics programs, and marketing technology ecosystems. Blends hands-on technical expertise with audience strategy, content operations, SEO, conversion optimization, and cross-functional leadership. Proven record of improving web performance, growing organic traffic and revenue, reducing marketing costs, and translating business goals into measurable digital experiences.',
  coreExpertise: [
    'Web Strategy & Governance',
    'SEO & Content Optimization',
    'CRO & A/B Testing',
    'CMS Administration',
    'Digital Campaign Strategy',
    'Analytics & KPI Reporting',
    'MarTech & CRM Integrations',
    'Tag Management',
    'UX & Customer Journeys',
    'Cross-Functional Leadership',
    'Vendor & Project Management',
    'Web Performance',
  ],
  experience: [
    keyed('crib-network', {
      _type: 'resumeExperience',
      section: 'professional',
      company: 'CRIB Network',
      role: 'Lead Systems Engineer & Digital Project Manager',
      startDate: '2022-01-01',
      current: true,
      location: 'Greater Phoenix Area',
      highlights: [
        'Lead end-to-end delivery of websites, digital products, campaign platforms, and customer-facing systems for clients across entertainment, nonprofit, and retail sectors.',
        'Translate marketing and business objectives into scalable web experiences, technical roadmaps, content workflows, and measurable launch plans.',
        'Direct cross-functional teams across design, engineering, content, and marketing, contributing to more than $15M in client revenue impact.',
        'Build and integrate automation, analytics, CRM, streaming, and reporting systems using modern web infrastructure, APIs, PostgreSQL, Redis, Docker, and FastAPI.',
        'Advise clients on digital strategy, user journeys, conversion opportunities, platform selection, and long-term web operations.',
      ],
    }),
    keyed('asu-edplus', {
      _type: 'resumeExperience',
      section: 'professional',
      company: 'EdPlus at Arizona State University',
      role: 'Manager, Marketing Technology',
      startDate: '2026-02-01',
      endDate: '2026-05-01',
      current: false,
      location: 'Scottsdale, AZ',
      highlights: [
        'Manage experimentation and personalization workflows across ASU Online web properties using Optimizely, including test setup, variants, QA, troubleshooting, and script debugging.',
        'Partner with product, UX, analytics, and marketing teams to define dataLayer, event-tracking, and MarTech requirements for new web experiences and campaigns.',
        'Implement and audit Google Tag Manager, custom scripts, Tealium CDP connectors, and behavioral data capture to improve tracking consistency and downstream reporting.',
        'Develop measurement strategies that resolve gaps in campaign attribution, user behavior data, and conversion reporting across the digital journey.',
        'Support onsite messaging and lead-generation programs through tools such as Wisepops, while applying SQL and BigQuery knowledge to analytics workflows.',
      ],
    }),
    keyed('arizona-science-center', {
      _type: 'resumeExperience',
      section: 'professional',
      company: 'Arizona Science Center',
      role: 'Website Manager / Integration Lead',
      startDate: '2023-11-01',
      endDate: '2026-02-01',
      current: false,
      location: 'Phoenix, AZ',
      highlights: [
        'Owned web strategy, governance, infrastructure, content operations, and optimization for a high-traffic educational organization.',
        'Directed a major website relaunch that improved performance scores by 30%, increased organic traffic by 23%, and supported measurable growth in online ticket sales.',
        'Improved customer journeys through SEO, A/B testing, analytics dashboards, content improvements, and conversion-focused UX recommendations.',
        'Integrated Tessitura CRM, Umbraco CMS, analytics, and supporting platforms to improve reporting, customer data visibility, and operational efficiency.',
        'Partnered with marketing, partnerships, membership, development, and executive teams while maintaining 99.9% uptime across digital environments.',
      ],
    }),
    keyed('ayr-digital-marketing-manager', {
      _type: 'resumeExperience',
      section: 'additional',
      company: 'Ayr Wellness Inc.',
      role: 'Digital Marketing Manager',
      startDate: '2021-06-01',
      endDate: '2022-02-01',
      current: false,
      location: 'Tempe, AZ',
      highlights: [
        'Led local and statewide digital marketing for multiple internally developed brands and three retail locations supporting more than $3M in monthly Arizona market revenue.',
        'Introduced in-house marketing capabilities and process improvements that reduced annual external-services spending by at least $120,000.',
        'Managed web design, campaign execution, KPI reporting, email, digital creative, print, packaging, billboards, and retail marketing programs.',
        "Partnered with retail teams on community marketing initiatives that contributed to multiple 2021 workplace and local 'Best of' recognitions.",
      ],
    }),
    keyed('ayr-marketing-specialist', {
      _type: 'resumeExperience',
      section: 'additional',
      company: 'Ayr Wellness Inc.',
      role: 'Marketing Specialist',
      startDate: '2019-10-01',
      endDate: '2021-06-01',
      current: false,
      location: 'Chandler, AZ',
      highlights: [
        'Designed, built, and maintained websites for multiple consumer brands while supporting email, social, print, packaging, and in-store marketing.',
        'Created campaign assets and brand systems that improved consistency across digital and physical customer touchpoints.',
      ],
    }),
    keyed('godaddy', {
      _type: 'resumeExperience',
      section: 'additional',
      company: 'GoDaddy',
      role: 'Product Specialist',
      startDate: '2018-07-01',
      endDate: '2019-10-01',
      current: false,
      location: 'Phoenix, AZ',
      highlights: [
        'Consulted small-business customers on websites, domains, email, and digital products while consistently generating at least $20,000 in monthly sales.',
        'Tested new products and sales workflows before broad release and translated technical features into practical customer solutions.',
      ],
    }),
    keyed('second-street', {
      _type: 'resumeExperience',
      section: 'additional',
      company: 'Second Street',
      role: 'Product Specialist',
      startDate: '2014-12-01',
      endDate: '2016-06-01',
      current: false,
      location: 'St. Louis, MO',
      highlights: [
        'Supported nearly 3,000 media and advertising partners, including iHeartMedia, USA TODAY, and Radio One, using an online promotions platform.',
        'Advised partners on audience growth, email acquisition, social engagement, sponsorship revenue, and digital promotion best practices.',
      ],
    }),
  ],
  education: [
    keyed('webster-ba', {
      _type: 'resumeEducation',
      institution: 'Webster University',
      credential: 'Bachelor of Arts, Communication & Media Studies',
      completionDate: '2014-05-01',
    }),
    keyed('webster-certificate', {
      _type: 'resumeEducation',
      institution: 'Webster University',
      credential: 'Certificate, Entrepreneurial & Small Business Operations',
      completionDate: '2011-05-01',
    }),
  ],
  platforms: [
    'Optimizely',
    'Google Analytics',
    'Google Tag Manager',
    'Google Search Console',
    'Tealium',
    'BigQuery',
    'SQL',
    'Tessitura CRM',
    'Umbraco CMS',
    'WordPress',
    'Wisepops',
    'HTML/CSS/JavaScript',
    'APIs',
    'PostgreSQL',
    'Redis',
    'Docker',
    'FastAPI',
  ],
}

const result = await client.createOrReplace(resume)
console.log(`Published ${result._id} at revision ${result._rev}`)
