export const metaDataKeywords = [
    "Front-end development",
    "Creative direction",
    "Web design",
    "Web development",
    "User experience (UX)",
    "User interface (UI)",
    "Responsive design",
    "Accessibility",
    "HTML",
    "CSS",
    "JavaScript",
    "Visual design",
    "Graphic design",
    "Branding",
    "Marketing",
    "Content creation",
    "Typography",
    "Animation",
    "Illustration",
    "Photography",
    "Video production",
    "Portfolio",
    "Wireframing",
    "Prototyping",
    "Usability testing",
    "SEO",
    "SEM",
    "Analytics",
    "Conversion optimization",
    "Mobile design",
    "App development",
    "AR/VR",
    "Game design",
    "Interaction design",
    "Information architecture",
    "Copywriting",
    "Social media",
    "E-commerce",
    "CMS",
    "Web hosting",
    "UI kits",
    "Style guides",
    "Design systems",
    "Version control",
    "Agile methodology",
    "Project management",
    "Client communication",
    "Team collaboration",
    "Remote work",
  ];
  